#################
### AUTOSTART ###
#################

# polkit agent
# exec-once = systemctl --user start hyprpolkitagent

# night light and gamma
# exec-once = hyprsunset

# idle managment deamon
# exec-once = hypridle

exec-once = noctalia-shell
