#############
### LOOKS ###
#############

general {
  gaps_in = 0
  gaps_out = 0

  border_size = 1
}

decoration {
  rounding = 0
}

group {
  groupbar {
    render_titles = false
    indicator_height = 2
    gaps_out = 1
    gaps_in = 12
    keep_upper_gap = false
  }
}

misc {
  force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
  disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}
