##################
### WORKSPACES ###
##################

###########
### LAYOUT

general {
  layout = scrolling
}

binds {
  movefocus_cycles_groupfirst = true # when in a grouped window, movefocus will cycle windows in the groups first
}

scrolling {
  fullscreen_on_one_column = true
  column_width = 0.5
  focus_fit_method = 1 # 0=center, 1=fit
  follow_focus = true
  follow_min_visible = 0.4
  explicit_column_widths = 0.333, 0.5, 0.667, 1.0
  direction = right
}

dwindle {
  pseudotile = true
  preserve_split = true
}

master {
  new_status = master
  mfact = 0.5
}

#################
### WINDOW RULES

# Ignore maximize requests from apps. You'll probably like this.
# windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
