$primary = rgb(ffdd33)
$surface = rgb(181818)
$secondary = rgb(96a6c8)
$error = rgb(f43841)
$tertiary = rgb(9e95c7)
$surface_lowest = rgb(1b1b1b)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
