require("options")
require("keymaps")

require("plugins-setup")

require("plugins.colorscheme")
require("plugins.comment")
-- require("plugins.indent-blankline")
require("plugins.autopairs")
require("plugins.gitsigns")
-- require("plugins.lsp")
-- require("plugins.cmp")
require("plugins.null_ls")
require("plugins.lsp-zero")
require("plugins.dap")
require("plugins.undotree")
require("plugins.lualine")
require("plugins.nvim-cmp")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.treesitter")
