#############
# WINDOW LAYOUTS
#

set $left h
set $down j
set $up k
set $right l

# Layout settings
layout_default_width 0.5
layout_default_height 1.0
layout_widths [0.33333333 0.5 0.666666667]
layout_heights [0.33333333 0.5 0.666666667]

# Move focus
bindsym $mod+$left focus left
bindsym $mod+$down focus down
bindsym $mod+$up focus up
bindsym $mod+$right focus right

# Layout mode
bindsym $mod+v set_mode v
bindsym $mod+c set_mode h

# Fullscreen & toggles
bindsym $mod+Shift+space fullscreen layout
bindsym $mod+space toggle_size this 1.0 1.0
bindsym $mod+Shift+f floating toggle
bindsym $mod+f focus mode_toggle

# Move windows
bindsym $mod+Shift+$left move left 250 px
bindsym $mod+Shift+$right move right 250 px
bindsym $mod+Shift+$up move up 150 px
bindsym $mod+Shift+$down move down 150 px

# Resize windows
bindsym $mod+equal cycle_size h next
bindsym $mod+minus cycle_size h prev
bindsym $mod+Shift+equal cycle_size v next
bindsym $mod+Shift+minus cycle_size v prev
# bindsym $mod+equal resize grow width 250 px
# bindsym $mod+minus resize shrink width 250 px
# bindsym $mod+Shift+equal resize grow height 150 px
# bindsym $mod+Shift+minus resize shrink height 150 px
# bindsym $mod+ctrl+$left resize shrink width 250 px
# bindsym $mod+ctrl+$right resize grow width 250 px
# bindsym $mod+ctrl+$up resize grow height 150 px
# bindsym $mod+ctrl+$down resize shrink height 150 px

# Overview
bindsym --no-repeat $mod+tab scale_workspace overview
# bindsym --whole-window $mod+Shift+tab scale_workspace overview

# Jump
bindsym --no-repeat $mod+semicolon jump
bindsym --no-repeat $mod+Shift+semicolon jump workspaces
bindsym --no-repeat $mod+Ctrl+semicolon jump floating

# Toggle pin
bindsym --no-repeat $mod+p pin beginning
bindsym --no-repeat $mod+Shift+p pin end

# Align
bindsym $mod+o align middle;

# Settings
maximize_if_single true

mode "fit_size" {
    bindsym w fit_size h visible proportional; mode default
    bindsym Shift+w fit_size v visible proportional; mode default
    bindsym Ctrl+w fit_size h visible equal; mode default
    bindsym Ctrl+Shift+w fit_size v visible equal; mode default

    bindsym $right fit_size h toend proportional; mode default
    bindsym Shift+$right fit_size v toend proportional; mode default
    bindsym Ctrl+$right fit_size h toend equal; mode default
    bindsym Ctrl+Shift+$right fit_size v toend equal; mode default

    bindsym $left fit_size h tobeg proportional; mode default
    bindsym Shift+$left fit_size v tobeg proportional; mode default
    bindsym Ctrl+$left fit_size h tobeg equal; mode default
    bindsym Ctrl+Shift+$left fit_size v tobeg equal; mode default

    bindsym $up fit_size h active proportional; mode default
    bindsym Shift+$up fit_size v active proportional; mode default
    bindsym Ctrl+$up fit_size h active equal; mode default
    bindsym Ctrl+Shift+$up fit_size v active equal; mode default

    bindsym $down fit_size h all proportional; mode default
    bindsym Shift+$down fit_size v all proportional; mode default
    bindsym Ctrl+$down fit_size h all equal; mode default
    bindsym Ctrl+Shift+$down fit_size v all equal; mode default
    bindsym Escape mode "default"
}
bindsym $mod+i mode "fit_size"
