#############
# APPEARANCE
#

font pango:JetBrainsMono Nerd Font 8

default_border pixel 1
gaps inner 0
gaps outer 0

# Animations
animations {
    enabled yes
    default yes 100
    # default yes 100 var 3 [ 0.215 0.61 0.355 1 ]
    # window_open yes 100 var 3 [ 0 0 1 1 ]
    # window_move yes 100 var 3 [ 0.215 0.61 0.355 1 ] off 0.05 6 [0 0.6 0.4 0 1 0 0.4 -0.6 1 -0.6]
    # window_size yes 100 var 3 [ -0.35 0 0 0.5 ]
    # You can also define curves for the following events
    # window_move_float
    # workspace_switch
    # window_fullscreen
    # overview
    # jump
}


# bar {
#   mode top
#
#   position top
#
#   # When the status_command prints a new line to stdout, scrollbar updates.
#   # The default just shows the current date and time.
#   status_command while date +'%d/%m/%Y %T'; do sleep 1; done
#
#   tray_padding 6
# }

## DEFAULT SWAY COLORS
# class                 border   backgr.  text    indicator child_border
# client.focused          #4c7899  #285577  #ffffff #2e9ef4   #285577
# client.focused_inactive #333333  #5f676a  #ffffff #484e50   #5f676a
# client.unfocused        #333333  #222222  #888888 #292d2e   #222222
# client.urgent           #2f343a  #900000  #ffffff #900000   #900000
# client.placeholder      #000000  #0c0c0c  #ffffff #000000   #0c0c0c
