#############
# WINDOW RULES & EXEC
#

# Floating windows
for_window [app_id="org.pulseaudio.pavucontrol"] floating enable

# Idle inhibit for fullscreen windows
for_window [all] inhibit_idle fullscreen

# Noctalia shell
exec noctalia-shell

# Polkit agent
# exec /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1

# Idle / swaylock
# exec swayidle -w \
#   timeout 300 'swaylock -f -c 000000' \
#   timeout 600 'scrollmsg "output * power off"' resume 'scrollmsg "output * power on"' \
#   before-sleep 'swaylock -f -c 000000'

# This will lock your screen after 300 seconds of inactivity, then turn off
# your displays after another 300 seconds, and turn your screens back on when
# resumed. It will also lock your screen before your computer goes to sleep.
