require("options")
require("keymaps")

require("plugins-setup")

require("plugins.colorscheme")
require("plugins.comment")
require("plugins.indent-blankline")
require("plugins.autopairs")
require("plugins.gitsigns")
require("plugins.null_ls")
require("plugins.lsp-zero")
require("plugins.dap")
require("plugins.undotree")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.alpha")
require("plugins.colorizer")
require("plugins.leap")
require("plugins.auto-save")
