require("modules/environment")
require("modules/programs")
require("modules/outputs")
require("modules/input")
require("modules/looks")
require("modules/workspaces")
require("modules/binds")
require("modules/autostart")
