general {
    lock_cmd = noctalia-shell ipc call lockScreen lock

    before_sleep_cmd = noctalia-shell ipc call lockScreen lock

    after_sleep_cmd = hyprctl dispatch dpms on
}

# 2) Dim screen (Noctalia)
listener {
    timeout = 120
    on-timeout = noctalia-shell ipc call brightness set 50
    on-resume  = noctalia-shell ipc call brightness set 100
}

# 2) Lock screen (Noctalia)
listener {
    timeout = 300
    on-timeout = noctalia-shell ipc call lockScreen lock
}

# 3) Screen off (DPMS)
listener {
    timeout = 360
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on
}

# 4) Suspend
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}

# 5) Hibernate
listener {
    timeout = 3600
    on-timeout = systemctl hibernate
}
