### OUTPUTS
source = ~/.config/hypr/modules/outputs.conf

### DEFAULT PROGRAMS
source = ~/.config/hypr/modules/programs.conf

### AUTOSTART
source = ~/.config/hypr/modules/autostart.conf

### ENVIRONMENT
source = ~/.config/hypr/modules/environment.conf

### PERMISSIONS
source = ~/.config/hypr/modules/permissions.conf

### LOOKS
source = ~/.config/hypr/modules/looks.conf

### WORKSPACES
source = ~/.config/hypr/modules/workspaces.conf

### INPUT
source = ~/.config/hypr/modules/input.conf

### KEYBINDINGS
source = ~/.config/hypr/modules/binds.conf

### NOCTALIA
source = ~/.config/hypr/noctalia/noctalia-colors.conf

