#############
# KEYBINDS
#

set $mod Mod4

# Floating modifier
floating_modifier $mod normal

# Launch apps
bindsym $mod+Return exec $term
bindsym $mod+q exec $browser
# bindsym $mod+e exec $file_manager

# Kill focused window
bindsym $mod+w kill

# Noctalia
bindsym $mod+a exec noctalia-shell ipc call launcher toggle
bindsym $mod+t exec noctalia-shell ipc call nightLight toggle
bindsym $mod+v exec noctalia-shell ipc call launcher clipboard
bindsym $mod+ESCAPE exec noctalia-shell ipc call sessionMenu toggle
bindsym $mod+SEMICOLON exec noctalia-shell ipc call controlCenter toggle
bindsym $mod+SHIFT+SEMICOLON exec noctalia-shell ipc call settings toggle
bindsym $mod+PERIOD exec noctalia-shell ipc call launcher emoji

bindsym --locked XF86AudioRaiseVolume exec noctalia-shell ipc call volume increase
bindsym --locked XF86AudioLowerVolume exec noctalia-shell ipc call volume decrease
bindsym --locked XF86AudioMute exec noctalia-shell ipc call volume muteOutput
bindsym --locked XF86AudioMicMute exec noctalia-shell ipc call volume muteInput
bindsym --locked XF86MonBrightnessUp exec noctalia-shell ipc call brightness increase
bindsym --locked XF86MonBrightnessDown exec noctalia-shell ipc call brightness decrease
bindsym --locked XF86AudioPlay exec noctalia-shell ipc call media playPause
bindsym --locked XF86AudioStop exec noctalia-shell ipc call media stop
bindsym --locked XF86AudioPrev exec noctalia-shell ipc call media previous
bindsym --locked XF86AudioNext exec noctalia-shell ipc call media next

# Screenshot
bindsym $mod+Control+s exec ~/.config/sway/scripts/screenshot-full.sh
bindsym $mod+s exec ~/.config/sway/scripts/screenshot-copy.sh
bindsym $mod+Shift+s exec ~/.config/sway/scripts/screenshot-save-copy.sh

# Reload sway
bindsym $mod+Shift+ESCAPE exec swaymsg reload
