#############
# INPUT DEVICES
#

# You can get the names of your inputs by running: swaymsg -t get_inputs

# Pointer
input "type:pointer" accel_profile flat

# Keyboard
input type:keyboard {
    xkb_layout us,rs(latinunicode),rs
    xkb_options grp:alt_shift_toggle,caps:escape,ctrl:swap_lalt_lctl,altwin:swap_ralt_rwin
    repeat_delay 200
    repeat_rate 40
}

input "type:touchpad" {
    # Enables "Tap to Click" (no need to physically press the touchpad down)
    tap enabled

    # Natural Scrolling: Moving fingers down scrolls the content up (Smartphone style)
    natural_scroll enabled

    # Middle Click Emulation: Pressing Left + Right click together acts as a Middle Click
    middle_emulation enabled

    # DWT (Disable While Typing): Prevents accidental palm clicks while you are using the keyboard
    dwt enabled

    # Tap Mapping: 1 finger = Left Click (l), 2 fingers = Right Click (r), 3 fingers = Middle Click (m)
    tap_button_map lrm

    # Drag Lock: When disabled, releasing your finger immediately drops the item you are dragging
    drag_lock disabled

    # Scrolling: Use two fingers anywhere on the pad to scroll
    scroll_method two_finger

    # Accel Profile: 'flat' provides 1:1 movement with no software acceleration
    # accel_profile "flat"

    # Pointer Speed: -1.0 is slowest, 1.0 is fastest, if accel flat just multiplier
    # pointer_accel 0.3

    # Click Method: 'clickfinger' makes 2-finger physical press a Right Click regardless of position
    click_method clickfinger
}
