[colors]
ansi = [
    "#181818",
    "#f43841",
    "#73c936",
    "#ffdd33",
    "#96a6c8",
    "#9e95c7",
    "#95a99f",
    "#e4e4ef",
]
background = "#181818"
brights = [
    "#52494e",
    "#ff4f58",
    "#73d936",
    "#ffdd33",
    "#96a6c8",
    "#afafd7",
    "#95a99f",
    "#f5f5f5",
]
compose_cursor = "#e4e4ef"
cursor_bg = "#e4e4ef"
cursor_border = "#e4e4ef"
cursor_fg = "#181818"
foreground = "#e4e4ef"
scrollbar_thumb = "#5f627f"
selection_bg = "#5f627f"
selection_fg = "#f4f4ff"
split = "#52494e"
visual_bell = "#181818"

[colors.indexed]
16 = "#96a6c8"
17 = "#e4e4ef"

[colors.tab_bar]
background = "#181818"
inactive_tab_edge = "#5f627f"

[colors.tab_bar.active_tab]
bg_color = "#ffdd33"
fg_color = "#181818"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#181818"
fg_color = "#e4e4ef"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#181818"
fg_color = "#e4e4ef"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#5f627f"
fg_color = "#e4e4ef"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#52494e"
fg_color = "#e4e4ef"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
author = "Noctalia"
name = "Noctalia"
